import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import { AuthProvider } from "./AuthProvider";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import StoreProvider from "@/Redux/storeProvider";
import Sidebar from "@/components/Sidebar";
import { ScrollArea } from "@/components/ui/scroll-area";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <StoreProvider>
          <body
            className={cn(
              "min-h-screen bg-background font-sans antialiased",
              fontSans.variable
            )}
          >
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <div className="flex h-screen w-full">
                <Sidebar />
                <ScrollArea className="flex-1 h-full overflow-y-auto">
                  <Navbar />
                  <main className="p-4">
                    {children}
                  </main>
                </ScrollArea>
              </div>
            </ThemeProvider>
          </body>
        </StoreProvider>
      </AuthProvider>
    </html>
  );
}
